spring.application.name=api-agendamentos

spring.datasource.url=jdbc:postgresql://localhost:5432/db_agendamento
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
# ddl-auto=create-drop
# ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=America/Belem

server.port=8080